PBP/CATATANKU WEB AND MOBILE/catatanku_web/catatanku/urls.py
from django.urls import path
from catatanku.views import show_main, create_note, show_json, show_json_by_id, create_note_flutter, delete_note_flutter, edit_note_flutter
from catatanku import views

app_name = "catatanku"

urlpatterns = [
    path('', show_main, name = "show_main"),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>/', show_json_by_id, name="show_json_by_id"),
    path('create/', create_note, name="create_note"),
    path('delete/', views.Delete.as_view(), name="delete"),
    path('edit/',views.Edit.as_view(), name = "edit" ),
    path('create_flutter/', create_note_flutter, name="create_note_flutter"),
    path('delete_flutter/<int:id>/',delete_note_flutter, name="delete_note_flutter"),
    path('edit_flutter/<int:id>/', edit_note_flutter, name="edit_note_flutter")
]

PBP/CATATANKU WEB AND MOBILE/catatanku_web/catatanku_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("catatanku.urls")),
]

PBP/CATATANKU WEB AND MOBILE/catatanku_web/catatanku/models.py
from django.db import models

# Create your models here.

class Notes(models.Model):
    title = models.CharField(max_length = 50)
    description = models.CharField(max_length = 10000)
    date = models.DateField(auto_now_add = True)
    time = models.TimeField(auto_now_add = True)

PBP/CATATANKU WEB AND MOBILE/catatanku_web/catatanku/forms.py
from django.forms import ModelForm
from catatanku.models import Notes

class NotesForm(ModelForm):
    class Meta:
        model = Notes
        fields = ["title", "description"]

PBP/CATATANKU WEB AND MOBILE/catatanku_web/catatanku/views.py
import json
from django.shortcuts import render
from catatanku.models import Notes
from catatanku.forms import NotesForm
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.core import serializers
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse


# Create your views here.
def show_main(request):
    notes_data = Notes.objects.all()
    context = {
        'list_of_notes': notes_data,
    }
    return render(request, "main.html", context)

def show_json(request):
    data = Notes.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = Notes.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="applicaton/json")

class Edit(View):
    def get(self, request):
        selectedId = request.GET.get('id', None)
        newTitle = request.GET.get('title', None)
        newDescription = request.GET.get('description', None)

        updatedNote = Notes.objects.get(id=selectedId)
        updatedNote.title = newTitle
        updatedNote.description = newDescription
        updatedNote.save()

        data = { 
            'edited':True,
            'newTitle': newTitle,
            'newDescription':newDescription,
        }
        return JsonResponse(data)

class Delete(View):
    def  get(self, request):
        id1 = request.GET.get('id', None)
        Notes.objects.get(id=id1).delete()
        data = {
            'deleted': True
        }
        return JsonResponse(data)


@csrf_exempt
def create_note(request):  
# create object of form
    form = NotesForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.save()
        data = Notes.objects.last()

        # parsing the form data into json
        result = {
            'id':data.id,
            'title':data.title,
            'description':data.description,
            'date': data.date,
            'time': data.time,
        }
        return JsonResponse(result)
    
    context = {'form': form}
    return render(request, "create.html", context)

@csrf_exempt
def create_note_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)

        new_note = Notes.objects.create(
            title = data["title"],
            description = data["description"]
        )

        new_note.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def delete_note_flutter(request, id):
    if request.method == 'DELETE':
        selectedId = id
        Notes.objects.get(id=selectedId).delete()
        return JsonResponse({"status": "success"}, status = 200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def edit_note_flutter(request, id):
    if request.method == 'PUT':
        selectedId = id
        data = json.loads(request.body)

        updatedNote = Notes.objects.get(id=selectedId)
        updatedNote.title = data["title"]
        updatedNote.description = data["description"]
        updatedNote.save()
        return JsonResponse({"status": "success"}, status = 200)
    else:
        return JsonResponse({"status": "error"}, status=401)

PBP/CATATANKU WEB AND MOBILE/catatanku_web/catatanku/templates/create.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Tambah Transaksi Baru</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Tambah"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

PBP/CATATANKU WEB AND MOBILE/catatanku_web/catatanku/templates/main.html
{% extends 'base.html' %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $.get("/json/", function(data) {
            for (ii=0; ii<data.length; ii++){
                $('#list_of_notes').append(`
                <div id="${data[ii].pk}" class="col-md-6 col-lg-4 mb-3">
                    <div class="card d-flex">
                        <div class="card-body d-flex flex-column">
                            <h5 id="${data[ii].pk}-title" class="card-title">${data[ii].fields.title}</h5>
                            <p hidden id="${data[ii].pk}-description" class="card-description">${data[ii].fields.description}</p>
                            <p class="card-text">${data[ii].fields.date}</p>
                            <p class="card-text">${data[ii].fields.time}</p>
                            <div class="row justify-content-end">
                                <div class="col-3">
                                    <button id="modify--${data[ii].pk}" class="btn btn-outline-info">Details</button>
                                </div>
                                <div class="col-3">
                                    <button onclick="deleteNote(${data[ii].pk})" class="btn btn-outline-danger">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                `)
            }
        });

        //href="/modify/${data[ii].pk}
        //<a href="/delete/${data[ii].pk}" class="btn btn-danger delete mb-2">
        //<button id="delete--${data[ii].pk}" onClick="deteleNote(${data[ii].pk})" class="btn btn-danger delete mb-2">

        $("#add_note").click(function(){
            $.post("/create/", {
                title: $("#title").val(),
                description: $("#description").val(),
            },
            function(result, status){
                if (status == 'success'){
                    $("#list_of_notes").append(`
                    <div id="${result.id}" class="col-md-6 col-lg-4 mb-3">
                    <div class="card d-flex">
                        <div class="card-body d-flex flex-column">
                            <h5 id="${result.id}-title" class="card-title">${result.title}</h5>
                            <p hidden id="${result.id}-description" class="card-description">${result.description}</p>
                            <p class="card-text">${result.date}</p>
                            <p class="card-text">${result.time}</p>
                            <div class="row justify-content-end">
                                <div class="col-3">
                                    <button id="modify--${result.id}" class="btn btn-outline-info">Details</button>
                                </div>
                                <div class="col-3">
                                    <button onclick="deleteNote(${result.id})" class="btn btn-outline-danger">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                    `);
                $('#title').val('')
                $('#description').val('')
                }
            })
        });

        $(document).on('click', 'button[id^="modify--"]', function(event){
            event.preventDefault();
            var id = $(this).closest('.card').parent().attr('id');
            var title = $(this).closest('.card').find('.card-title').text();
            var description = $(this).closest('.card').find('.card-description').text();

            $('#detail_id').text(id);
            $('#detail_title').text(title);
            $('#detail_description').text(description);
            $('#detail_modal').modal('show');
        });

        $('#edit_button').click(function(){
            event.preventDefault();
            var id = $(this).parent().parent().find('#detail_id').text();
            var title = $(this).parent().parent().find('#detail_title').text();
            var description = $(this).parent().parent().find('#detail_description').text();

            $('#edit_id').text(id);
            $('#edit_title').val(title);
            $('#edit_description').val(description);
        });

    });

    function deleteNote(id) {
        $.ajax({
            url: '{% url "catatanku:delete" %}',
            data: {
                'id': id,
            },
            dataType: 'json',
            success: function (data) {
                if (data.deleted) {
                $("#list_of_notes #" + id).remove();
                }
            }
        });
    }

    function editNote(){

        var id = $('#edit_id').text().trim();
        var newTitle = $('#edit_title').val().trim();
        var newDescription = $('#edit_description').val().trim();

        $.ajax({
            url: '{% url "catatanku:edit" %}',
            data: {
                'id': id,
                'title': newTitle,
                'description': newDescription,
            },
            dataType: 'json',
            success: function(data) {
                if (data.edited) {
                    $("#" + id + "-title").text(newTitle);
                    $("#" + id + "-description").text(newDescription);
                    $("#detail_title").text(newTitle);
                    $("#detail_description").text(newDescription);
                }
            },
            error: function(xhr, textStatus, errorThrown) {
                console.log('AJAX error:', errorThrown);
            }
        });
    }
    
</script>

<!-- Button for form modal -->
<button type="button" class="btn btn-outline-light sticky-bottom position-fixed end-0 mb-3 me-3 fs-5 bg-dark" data-bs-toggle="modal" data-bs-target="#form_modal">
    New Note
</button>

<!-- Form Modal -->
<div class="modal fade" id="form_modal" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content rounded-3 shadow">
            <div class="modal-header border-bottom-1 mx-3 pb-1">
                <div class="h4">New Note</div>
                <button type="button" class=" btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body mx-3 border-bottom-0">
                    {% csrf_token %}
                    <div class="mb-0">
                        <label for="title" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title" name="title"></input>    
                    </div>
                    <div class="mb-0">
                        <label for="description" class="col-form-label">Desctiption:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
            </div>
            <div class="modal-footer mx-3 border-top-0">
                <button type="submit" class="btn btn-outline-light" id="add_note" data-bs-dismiss="modal">Add note</button>
            </div>
        </div>
    </div>
</div>

<!-- WebSite Header -->
<header class="container-fluid text-center sticky-top py-3 border-bottom bg-dark" >
    <div class="row">
        <div class="col">
            <div class="h2">Catatanku!</div>
        </div>
    </div>
</header>

<!-- Main Body contains List of Notes as Cards -->
<main class="row m-3" id="list_of_notes"></main>

<!-- Detail Modal -->
<div class="modal fade" id="detail_modal">
    <div class="modal-dialog">
        <div class="modal-content rounded-3 shadow">
            <div class="modal-header border-bottom-1 mx-3 pb-1">
                <h5 class="modal-title" id="detail_title"></h5>
                <h5 hidden id="detail_id"></h5>
            <button type="button" class=" btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body mx-3 border-bottom-0">
                <div class="mb-0">
                    <p id="detail_description"></p>  
                </div>
            </div>
        <div class="modal-footer mx-3">
          <button type="button" class="btn btn-outline-light" id="edit_button" data-bs-toggle="modal" data-bs-target="#edit_modal">Edit</button>
        </div>
      </div>
    </div>
</div>

<!-- Edit Modal -->
<div class="modal fade" id="edit_modal" data-bs-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content rounded-3 shadow">
        <div class="modal-header border-bottom-1 mx-3 pb-1">
          <h5 class="modal-title">Edit Note</h5>
        </div>
        <div class="modal-body mx-3 border-bottom-0">
          <form id="modifyForm">
            <div class="form-group">
              <label for="modifyTitle">Title:</label>
              <input type="text" class="form-control" id="edit_title"></input>
              <label for="modifyDescription">Description:</label>
              <textarea type="text" class="form-control" id="edit_description"></textarea>
            </div>
          </form>
        </div>
        <div class="modal-footer mx-3 border-top-0">
          <p hidden id="edit_id"></p>
          <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#detail_modal">Cancel</button>
          <button type="button" class="btn btn-outline-primary" id="edit_submit" onclick="editNote()" data-bs-toggle="modal" data-bs-target="#detail_modal">Submit</button>
        </div>
      </div>
    </div>
</div>


{% endblock content %}

PBP/CATATANKU WEB AND MOBILE/catatanku_web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en"  data-bs-theme="dark">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
{% block meta %}
{% endblock meta %}
</head>

<body>
{% block content %}
{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>

</html>